Fix build, use layout API and conform to Haiku coding style.
HaikuArchives/BeDead pull request #1
Opened 2017-04-23 17:51 UTC by AkshayAgarwal007

2017-04-23 17:52 UTC, AkshayAgarwal007 commented
![bedead](https://cloud.githubusercontent.com/assets/8170214/25315963/a735e3ee-287b-11e7-9996-61cf986711e6.png)

2017-04-23 18:07 UTC, humdingerb requested changes
If you're serious with the Haiku coding style guide... :)

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +			 B_AUTO_UPDATE_SIZE_LIMITS | B_WILL_ACCEPT_FIRST_CLICK)
Only one indent.

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +					B_WILL_DRAW);
Only one indent.

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +	fDeathScroll = new BScrollView("scroll_death", fDeathList,							B_WILL_DRAW, false, true);
Newline + one indent.

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +	fCloseCheck->AttachedToWindow();
I've never seen the hook AttachedToWindow() being explicitely called. Is this really necessary?

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +
cases need extra { } as there are more than one instructions in the case blocks.

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +		{	int32 index;
{ on a separate line.

2017-04-23 18:07 UTC, humdingerb commented on src/DeathWindow.cpp
> +	if(fCloseCheck->Value())
space after "if".

2017-04-23 18:35 UTC, AkshayAgarwal007 commented
Updated...
Despite how much I try to avoid them either you or @waddlesplash always catch some coding style mistakes in my PRs :)

2017-04-23 18:40 UTC, AkshayAgarwal007 commented
It's marked as freeware, so what should be included in the license headers?

2017-04-24 16:37 UTC, humdingerb commented
I guess you can try to contact the author at retroj@iserv.net, but I doubt the address will work after 18 years. The website isn't there anymore anyway...

@waddlesplash , what to do in such a case? Use MIT until we hear back otherwise?

2017-04-24 22:56 UTC, waddlesplash commented
Don't put any license and just have the copyright dates and original author.

2017-04-29 18:28 UTC, AkshayAgarwal007 commented
I've added the Copyright headers.

2017-04-30 01:26 UTC, scottmc commented
@waddlesplash, any idea where this came from and whether permission was given by the original author to post it here?  How do we know it is "open source"?  Did the original author send it to anyone via email with permission and if so what license did they agree too?  These are key things we should be asking of every program we post here.

2017-04-30 09:31 UTC, clasqm commented
@scottmc I  am the one who uploaded it, and no, I am not the original author. I agree that it is something we need to think about these days, and at least if we have it, there is a chance of finding the original author and asking them. But these programs come from a more innocent time, when we were not yet all obsessed with licensing.

2017-05-02 17:20 UTC, merged